### ISSUE TITLE
make login modal be pretty

### ISSUE THREAD

**Issue by Maigard** [Samsinite/tri-conf-2015-app#30]

**Comment by SquidAndCrow** [comment]
I'm not even sure where to start with this...

**Comment by Maigard** [comment]
@SquidAndCrow Was the stopping block figuring out where the template is? If so, it is in app/templates/components/login-modal.hbs

**Comment by SquidAndCrow** [comment]
Ah, thanks! I was looking at the window that pops up with you click the login button. Didn't realize there was a modal for trying to use functions if not logged in. On it!

**Comment by Maigard** [comment]
oh yeah, that makes sense. I forgot about that popup.
